/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edusys_project.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrameStudyPlanManagementMaintenance extends javax.swing.JFrame {

    /**
     * Creates new form FrameStudyPlanManagementMaintenance
     */
    public FrameStudyPlanManagementMaintenance() {
        initComponents();
    }

    public PanelCRUD getPanelCRUD1() {
        return panelCRUD1;
    }

    public PanelStudyPlanManagementAndMaintenance getPanelStudyPlanManagementAndMaintenance1() {
        return panelStudyPlanManagementAndMaintenance1;
    }

    public void showMessage(String message){
        JOptionPane.showMessageDialog(null, message);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCRUD1 = new edusys_project.view.PanelCRUD();
        panelStudyPlanManagementAndMaintenance1 = new edusys_project.view.PanelStudyPlanManagementAndMaintenance();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCRUD1.setOpaque(false);
        getContentPane().add(panelCRUD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, -1, -1));

        panelStudyPlanManagementAndMaintenance1.setOpaque(false);
        getContentPane().add(panelStudyPlanManagementAndMaintenance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private edusys_project.view.PanelCRUD panelCRUD1;
    private edusys_project.view.PanelStudyPlanManagementAndMaintenance panelStudyPlanManagementAndMaintenance1;
    // End of variables declaration//GEN-END:variables
}
