/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edusys_project.view;

import edusys_project.controller.tables.*;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author valer
 */
public class FrameStudyPlan extends javax.swing.JFrame {

    /**
     * Creates new form FrameStudyPlan
     */
    
    public FrameStudyPlan(StudyPlanTableController controller) {
        initComponents();
        listen(controller);
    }
    
    public FrameStudyPlan() {
        initComponents();
    }


    public void listen(ActionListener controller) {
        downloadBtn.addActionListener(controller);
        editStudyPlanBtn.addActionListener(controller);
        BackBtn.addActionListener(controller);
    }

    public void showMessage(String message){
        JOptionPane.showMessageDialog(null,message);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackBtn = new javax.swing.JButton();
        panelTableStudyPlan1 = new edusys_project.view.PanelTableStudyPlan();
        descriptionLabel = new javax.swing.JLabel();
        effectiveDateLabel = new javax.swing.JLabel();
        approvalDateLabel = new javax.swing.JLabel();
        creditsLabel = new javax.swing.JLabel();
        downloadBtn = new javax.swing.JButton();
        editStudyPlanBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackBtn.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("Back");
        BackBtn.setBorderPainted(false);
        BackBtn.setContentAreaFilled(false);
        BackBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        panelTableStudyPlan1.setOpaque(false);
        getContentPane().add(panelTableStudyPlan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 120, 820, -1));
        getContentPane().add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 570, 180));
        getContentPane().add(effectiveDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 100, 20));
        getContentPane().add(approvalDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 100, 20));
        getContentPane().add(creditsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 100, 20));

        downloadBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/downloadBtn.png"))); // NOI18N
        downloadBtn.setActionCommand("downloadBtn");
        downloadBtn.setBorderPainted(false);
        downloadBtn.setContentAreaFilled(false);
        getContentPane().add(downloadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, -1, -1));

        editStudyPlanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/EditIcon.png"))); // NOI18N
        editStudyPlanBtn.setActionCommand("editStudyPlanBtn");
        editStudyPlanBtn.setBorderPainted(false);
        editStudyPlanBtn.setContentAreaFilled(false);
        getContentPane().add(editStudyPlanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/STUDY PLANStxt.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoBlancoSobreTurquesa.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoGrandeTurquesa.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel approvalDateLabel;
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JButton downloadBtn;
    private javax.swing.JButton editStudyPlanBtn;
    private javax.swing.JLabel effectiveDateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private edusys_project.view.PanelTableStudyPlan panelTableStudyPlan1;
    // End of variables declaration//GEN-END:variables
}
