/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edusys_project.view;

import javax.swing.JOptionPane;

/**
 *
 * @author fcama
 */
public class Frame_MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form Frame_MainMenu
     */
    public Frame_MainMenu() {
        initComponents();
    }

    public Panel_Buttons_Menu getPanel_Buttons_Menu1() {
        return panel_Buttons_Menu1;
    }

    public Panel_Nav_Menu getPanel_Nav_Menu1() {
        return panel_Nav_Menu1;
    }
    
    public void showMessage(String message){
        JOptionPane.showMessageDialog(null, message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Nav_Menu1 = new edusys_project.view.Panel_Nav_Menu();
        panel_Buttons_Menu1 = new edusys_project.view.Panel_Buttons_Menu();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panel_Nav_Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel_Buttons_Menu1.setOpaque(false);
        getContentPane().add(panel_Buttons_Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoCelesteGrande.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private edusys_project.view.Panel_Buttons_Menu panel_Buttons_Menu1;
    private edusys_project.view.Panel_Nav_Menu panel_Nav_Menu1;
    // End of variables declaration//GEN-END:variables
}
