/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edusys_project.view;

import java.awt.event.ActionListener;

/**
 *
 * @author Usuario
 */
public class PanelBtnSingIn extends javax.swing.JPanel {

    /**
     * Creates new form PanelBtnSingIn
     */
    public PanelBtnSingIn() {
        initComponents();
    }

    public void listen(ActionListener controller){
        btnBack.addActionListener(controller);
        btnLogin.addActionListener(controller);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Log-in.png"))); // NOI18N
        btnLogin.setActionCommand("login");
        btnLogin.setContentAreaFilled(false);
        add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back2.png"))); // NOI18N
        btnBack.setActionCommand("back");
        btnBack.setContentAreaFilled(false);
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 267, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    // End of variables declaration//GEN-END:variables
}
