/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edusys_project.view;

import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class PanelStudyPlanManagementAndMaintenance extends javax.swing.JPanel {

    /**
     * Creates new form PanelCareersManagementMaintenance
     */
    public PanelStudyPlanManagementAndMaintenance() {
        initComponents();
    }

    public String getApprovalDateTxt() {
        return approvalDateTxt.getText();
    }

    public void setApprovalDateTxt(String approvalDateTxt) {
        this.approvalDateTxt.setText(approvalDateTxt);
    }

    public String getDescriptionStudyPlanTxt() {
        return descriptionStudyPlanTxt.getText();
    }

    public void setDescriptionStudyPlanTxt(String descriptionStudyPlanTxt) {
        this.descriptionStudyPlanTxt.setText(descriptionStudyPlanTxt);
    }

    public String getEffectiveDateTxt() {
        return effectiveDateTxt.getText();
    }

    public void setEffectiveDateTxt(String effectiveDateTxt) {
        this.effectiveDateTxt.setText(effectiveDateTxt);
    }

    public String getIdStudyNameTxt() {
        return idStudyNameTxt.getText();
    }

    public void setIdStudyNameTxt(String idStudyNameTxt) {
        this.idStudyNameTxt.setText(idStudyNameTxt);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idStudyNameTxt = new javax.swing.JTextField();
        descriptionStudyPlanTxt = new javax.swing.JTextField();
        approvalDateTxt = new javax.swing.JTextField();
        effectiveDateTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idStudyNameTxt.setBorder(null);
        add(idStudyNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 120, 80, 20));

        descriptionStudyPlanTxt.setBorder(null);
        add(descriptionStudyPlanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 240, 50));

        approvalDateTxt.setBorder(null);
        add(approvalDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 230, 30));

        effectiveDateTxt.setBorder(null);
        add(effectiveDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 240, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TituloPlanDeEstudios.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 14, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Id Study Plan_.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 131, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Approval date_.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 302, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Description_.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 198, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Effective Date_.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 378, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtPequeño.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 112, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtGrande.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 224, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TextArea.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 328, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TextArea.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 401, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField approvalDateTxt;
    private javax.swing.JTextField descriptionStudyPlanTxt;
    private javax.swing.JTextField effectiveDateTxt;
    private javax.swing.JTextField idStudyNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
