/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edusys_project.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrameSign_In extends javax.swing.JFrame {

    /**
     * Creates new form FrameSing_In
     */
    public FrameSign_In() {
        initComponents();
    }

    public PanelBtnSingIn getPanelBtnSingIn1() {
        return panelBtnSingIn1;
    }

    public Panel_Nav getPanel_Nav1() {
        return panel_Nav1;
    }

    public PanelTxtSignIn getPanelTxtSingIn1() {
        return panelTxtSingIn1;
    }

    public void showMessage(String message){
        JOptionPane.showMessageDialog(null, message);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Nav1 = new edusys_project.view.Panel_Nav();
        panelTxtSingIn1 = new edusys_project.view.PanelTxtSignIn();
        panelBtnSingIn1 = new edusys_project.view.PanelBtnSingIn();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panel_Nav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelTxtSingIn1.setOpaque(false);
        getContentPane().add(panelTxtSingIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 290, -1));

        panelBtnSingIn1.setOpaque(false);
        getContentPane().add(panelBtnSingIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoCelesteGrande.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private edusys_project.view.PanelBtnSingIn panelBtnSingIn1;
    private edusys_project.view.PanelTxtSignIn panelTxtSingIn1;
    private edusys_project.view.Panel_Nav panel_Nav1;
    // End of variables declaration//GEN-END:variables
}
